// range-data.js — PUTTING, CHIPPING, WARMUP_DATA arrays
// ═══════════════════════════════════════════
//  COMBINE DATA
// ═══════════════════════════════════════════
const PUTTING = [
  {id:'p1',name:'3ft — Uphill Straight',sub:'The most makeable putt. Build confidence here.',
   setup:['Find a hole with a gentle uphill slope — ball rolls slightly away from you toward the hole.','Place a tee 3 feet (one putter length) directly below the hole on the fall line.','This putt rewards a square face and solid tempo. Start here to find your rhythm.'],
   tip:'Focus on keeping the putterface square through impact. Uphill putts forgive speed errors — direction is what matters here.',
   video:'https://www.youtube.com/results?search_query=uphill+straight+putt+practice+golf+fundamentals'},
  {id:'p2',name:'3ft — Downhill Straight',sub:'Same distance, harder test. Speed control is everything.',
   setup:['Find a hole where you putt directly downhill — gravity assists the ball toward the hole.','Place a tee 3 feet directly above the hole on the fall line.','This putt requires a very soft stroke — expect it to accelerate as it rolls.'],
   tip:'Shorten your backstroke significantly on downhill putts. The green does the work. Your only job is to start it on line with the right pace.',
   video:'https://www.youtube.com/results?search_query=downhill+putt+speed+control+golf+practice+soft+stroke'},
  {id:'p3',name:'3ft — Sidehill Left-to-Right',sub:'The most commonly missed short putt. Ball breaks away from you.',
   setup:['Find a spot where the slope runs left to right as you face the hole — your left foot feels higher.','Place a tee 3 feet to the left of the hole (the high side).','The ball breaks toward the right as it slows. Aim left of center.'],
   tip:'Golfers miss most putts on the low side — they don\'t play enough break. On a left-to-right putt, commit to aiming outside the left edge of the hole.',
   video:'https://www.youtube.com/results?search_query=left+to+right+3+foot+breaking+putt+practice+AimPoint'},
  {id:'p4',name:'3ft — Sidehill Right-to-Left',sub:'Ball breaks toward you. Many players over-read this side.',
   setup:['Find a spot where the slope runs right to left as you face the hole — your right foot feels higher.','Place a tee 3 feet to the right of the hole (the high side).','The ball breaks toward you. Aim outside the right edge.'],
   tip:'Right-to-left putts often look like they break less than they do. Use AimPoint to calibrate — most players under-read both break directions.',
   video:'https://www.youtube.com/results?search_query=right+to+left+3+foot+breaking+putt+practice+green+reading'},
  {id:'p5',name:'6ft — Uphill Breaking',sub:'Scoring range. Make these and your card improves immediately.',
   setup:['Find a hole with a combined uphill and breaking slope — both uphill and to one side.','Pace off 6 feet from the hole on the high-side diagonal.','This putt is more forgiving on speed but requires a precise break read.'],
   tip:'Uphill breaking putts break less than they appear because you must hit them firmer. If using AimPoint, your finger count may feel like one less than expected.',
   video:'https://www.youtube.com/results?search_query=6+foot+uphill+breaking+putt+golf+practice+scoring+range'},
  {id:'p6',name:'6ft — Downhill Breaking',sub:'The hardest station in this combine. Respect it.',
   setup:['Find a hole with a combined downhill and breaking slope.','Pace off 6 feet from the hole on the high side with slope running away from you.','This requires the softest stroke and the most break of any station so far.'],
   tip:'Downhill breaking putts break 3–4x more than uphill putts of the same slope because the ball slows more. Play WAY more break than you think.',
   video:'https://www.youtube.com/results?search_query=downhill+breaking+putt+6+feet+golf+speed+control'},
  {id:'p7',name:'6ft — Left-to-Right',sub:'Pure sidehill at scoring distance.',
   setup:['Find a pure sidehill slope — flat in terms of uphill/downhill, just tilted left to right.','Place a tee 6 feet directly on the high side of the hole.','The ball breaks steadily across the green toward the low side.'],
   tip:'On sidehill putts the break is consistent through the roll. Aim outside the hole and commit fully — second-guessing mid-stroke is the kiss of death.',
   video:'https://www.youtube.com/results?search_query=sidehill+left+right+6+foot+putt+golf+aim+line'},
  {id:'p8',name:'6ft — Right-to-Left',sub:'Opposite sidehill. Check your dominant miss direction.',
   setup:['Same as station 7 but reversed — place your tee 6 feet on the right high side.','The ball breaks from right to left across the green.','Compare your results vs station 7 to identify a dominant miss direction.'],
   tip:'Compare make % on L→R vs R→L over multiple sessions. Most golfers have a dominant miss side their brain compensates for. Data reveals what feel hides.',
   video:'https://www.youtube.com/results?search_query=right+to+left+6+foot+putt+practice+golf'},
  {id:'p9',name:'10ft — Uphill Moderate',sub:'Birdie range. You should be making about 1 in 3.',
   setup:['Find a 10-foot uphill putt with moderate break — 1–2% slope if using a tool.','Pace off 10 feet from the hole. Two putter lengths plus an extra 4 feet.','Focus on a confident, committed stroke. Uphill putts reward aggression.'],
   tip:'Tour pros make ~43% from 10 feet uphill. A 10-handicapper should aim to make 1 in 3. If making 0, speed control is the issue — you\'re leaving them short.',
   video:'https://www.youtube.com/results?search_query=10+foot+uphill+putt+golf+make+percentage+practice'},
  {id:'p10',name:'10ft — Downhill Moderate',sub:'The most feared putt in amateur golf. Own it.',
   setup:['Find a 10-foot downhill putt with moderate break — genuinely challenging even for scratch players.','Place your tee 10 feet above the hole on the high side.','Primary goal: give yourself a tap-in on a miss. Never run it 5 feet past.'],
   tip:'On a 10-foot downhill putt your backstroke should be barely more than for a 4-footer. Think "die it at the hole." Speed first, line second.',
   video:'https://www.youtube.com/results?search_query=10+foot+downhill+putt+golf+speed+control+how+to'},
  {id:'p11',name:'10ft — Left-to-Right',sub:'Green reading at distance. Trust your read or trust your feet.',
   setup:['Find a 10-foot pure sidehill putt breaking left to right.','Place your tee 10 feet on the high side (left side) of the hole.','If using AimPoint, feel the slope at the midpoint and use your fingers to find the aim point.'],
   tip:'At 10 feet the invisible break is very significant. Most golfers play 2–3 inches when the putt actually breaks 8–10 inches. Use your feet, not just your eyes.',
   video:'https://www.youtube.com/results?search_query=AimPoint+Express+10+foot+breaking+putt+practice'},
  {id:'p12',name:'10ft — Right-to-Left',sub:'Final station. Finish strong.',
   setup:['10-foot right-to-left putt. Place tee on the right high side, 10 feet from the hole.','Go through your full pre-shot routine on every putt — this is the last station.','Log your miss direction accurately. This data drives future prescriptions.'],
   tip:'Compare your 10-foot make rates across all 4 directions in your history. The direction with the lowest make % is where your game prescriptions will focus.',
   video:'https://www.youtube.com/results?search_query=right+to+left+10+foot+putt+golf+green+reading+practice'}
];

const CHIPPING = [
  {id:'c1',name:'5 yds — Tight Lie',sub:'The basic chip. No excuses from here.',
   setup:['Drop ball in tight-mown fairway or collar, 5 yards from green edge.','Choose a hole roughly 15–20 feet onto the green — enough room to roll.','Use minimum loft to carry the fringe and let the ball run to the hole.'],
   tip:'From a tight lie, less loft is your friend. A 52° or pitching wedge gives more margin for error than the 60°, which demands perfect contact every time.',
   video:'https://www.youtube.com/results?search_query=TPI+chipping+tight+lie+technique+less+loft+golf'},
  {id:'c2',name:'5 yds — Light Rough',sub:'Same distance, slightly more cushion under the ball.',
   setup:['Find light rough 5 yards from the green — grass sits slightly under the ball.','Same target hole as station 1 for direct comparison.','The rough may produce a flier — ball comes out with less spin and more roll.'],
   tip:'From light rough you can still use a lower-lofted club, but expect slightly less spin. The ball rolls further after landing — adjust your landing zone accordingly.',
   video:'https://www.youtube.com/results?search_query=chipping+from+light+rough+golf+technique+distance+control'},
  {id:'c3',name:'10 yds — Tight Lie',sub:'The most common chip distance. Face this constantly.',
   setup:['Drop ball 10 yards from green edge on tight-mown area.','Pick a hole with moderate green to work with — 10–25 feet of surface.','Visualize landing spot first — roughly 1/3 of the way to the hole for bump-and-run.'],
   tip:'Good chippers move their body UPWARD through impact — not downward like a full swing. Lead with the handle, keep shaft slightly forward, let the bounce do its job.',
   video:'https://www.youtube.com/results?search_query=TPI+chipping+10+yards+body+upward+through+impact'},
  {id:'c4',name:'10 yds — Light Rough',sub:'Flier risk zone. Club selection is critical.',
   setup:['Drop ball 10 yards from green in light rough.','Same target hole as station 3 — compare results directly.','If ball sits down at all, you need more loft to get through grass cleanly.'],
   tip:'Track club choice here vs station 3 and compare proximity. Many golfers use the same club from rough as tight lie and get worse results. The data will show it.',
   video:'https://www.youtube.com/results?search_query=chipping+from+rough+lie+club+selection+golf+flier'},
  {id:'c5',name:'10 yds — Upslope',sub:'Ball goes higher, flies shorter, rolls less. Adjust your club.',
   setup:['Find a 10-yard chip where the ground slopes upward toward the green.','Your front foot is higher than your back foot at address.','The upslope effectively adds loft to whatever club you use.'],
   tip:'From an upslope, consider going up one club (less loft) to counteract the added dynamic loft. Ball lands softer and shorter than normal even with lower loft.',
   video:'https://www.youtube.com/results?search_query=uphill+lie+chip+shot+golf+upslope+technique+adjustment'},
  {id:'c6',name:'10 yds — Downslope',sub:'The hardest chipping station. Technically demanding.',
   setup:['Find a 10-yard chip where ground slopes downward toward the green.','Your front foot is lower than your back foot. Ball wants to get under the club.','Play ball back in stance and keep more weight on front foot at address.'],
   tip:'From a downslope your priority is solid contact. Ball back, hands forward, chase the slope through impact. Expect the ball to run more than normal — plan for it.',
   video:'https://www.youtube.com/results?search_query=downhill+lie+chip+shot+golf+downslope+technique'},
  {id:'c7',name:'20 yds — Tight Lie',sub:'Pitch/chip boundary. Club selection is a real decision.',
   setup:['20 yards from green edge on tight fairway or mown collar.','You have a genuine choice: bump-and-run with a mid-iron, or carry with a wedge.','Pick a hole that allows both low and high shot shapes to work.'],
   tip:'At 20 yards, track which loft gives best proximity consistently. Many golfers default to 60° here but data often shows the 52° or even 9-iron delivers better results.',
   video:'https://www.youtube.com/results?search_query=20+yard+chip+shot+golf+club+selection+bump+run+vs+wedge'},
  {id:'c8',name:'20 yds — Light Rough',sub:'Flier lies become more consequential at this distance.',
   setup:['20 yards in light rough — same target as station 7.','Extra distance magnifies flier effect — ball can fly 5–8 yards further than expected.','Take one more club (less loft) and choke down slightly for control.'],
   tip:'From rough at 20 yards, controlling landing zone is paramount. Hit to a spot, not to the hole. Reliably land within 3 feet of your spot and the roll handles itself.',
   video:'https://www.youtube.com/results?search_query=20+yard+chip+from+rough+landing+zone+control+golf'},
  {id:'c9',name:'20 yds — Fringe',sub:'Putt, chip, or hybrid? The decision matters.',
   setup:['Place ball on fringe — slightly longer grass between fairway and green.','20 yards is typically too far to putt reliably, but fringe can work fine for chip.','Consider a hybrid or low-lofted iron for a bump-and-run through the fringe.'],
   tip:'From fringe at 20 yards, a hybrid bump-and-run is often the highest-percentage shot. Gets ball rolling immediately and removes risk of poor chip contact.',
   video:'https://www.youtube.com/results?search_query=fringe+20+yards+chip+vs+putt+vs+hybrid+bump+run+golf'},
  {id:'c10',name:'30 yds — Tight Lie',sub:'Scoring distance. Birdie range if you stick it.',
   setup:['30 yards from green edge on tight-mown lie.','At this distance most players use a wedge with a 3/4 swing — not a full swing.','Pick a specific target hole and track proximity on every shot.'],
   tip:'Control the carry distance first — the landing zone determines everything. If you can land consistently in a 5-foot circle at 30 yards, proximity results will follow.',
   video:'https://www.youtube.com/results?search_query=30+yard+chip+pitch+golf+distance+control+landing+zone'},
  {id:'c11',name:'30 yds — Light Rough',sub:'Your most common course situation. Practice it like it matters.',
   setup:['30 yards from green in light rough — one of the most common short game situations on a real course.','Use a sand wedge or higher loft to get through the grass cleanly.','Go through your full pre-shot routine — landing spot, club selection, commitment.'],
   tip:'This is your most common real-world chip. If proximity here is consistently poor, this station becomes your game prescription trigger for Darts or Dollar Signs.',
   video:'https://www.youtube.com/results?search_query=30+yard+chip+from+rough+golf+wedge+technique+landing+spot'},
  {id:'c12',name:'30 yds — Upslope',sub:'Distance drops on upslopes. Avoid leaving it short.',
   setup:['30 yards upslope — the green is above you, natural tendency is to leave it short.','You need more club or more swing than from a flat lie at the same distance.','Use the upslope to help you commit — the slope produces a softer landing naturally.'],
   tip:'At 30 yards uphill most players under-club. Take one more club than you think and make a full committed swing. The slope kills distance — let the extra club compensate.',
   video:'https://www.youtube.com/results?search_query=30+yard+uphill+chip+pitch+golf+upslope+distance+control'}
];

const WARMUP_DATA = [
  {name:'90/90 Hip Stretch',desc:'Sit on the ground with both knees at 90 degrees, one in front and one to the side. Opens the hip capsule — critical for rotation.',reps:'30 sec each side',link:'https://www.youtube.com/results?search_query=TPI+90+90+hip+stretch+golf+mobility'},
  {name:'Thoracic Rotation',desc:'On hands and knees, place one hand behind your head and rotate elbow toward the sky. Opens thoracic spine for backswing.',reps:'10 reps each side',link:'https://www.youtube.com/results?search_query=TPI+thoracic+spine+rotation+golf+mobility'},
  {name:'Glute Bridge',desc:'Lying on your back, drive hips toward the ceiling, squeezing glutes at the top. Activates your primary power muscles.',reps:'15 reps',link:'https://www.youtube.com/results?search_query=TPI+glute+bridge+golf+activation+power'},
  {name:'Leg Swings',desc:'Hold a club for balance and swing each leg forward and back like a pendulum, increasing range of motion gradually.',reps:'15 swings each leg',link:'https://www.youtube.com/results?search_query=TPI+leg+swings+golf+warmup+hip+mobility'},
  {name:'Shoulder Cross-Body',desc:'Pull each arm across your chest to open the posterior shoulder capsule — critical for backswing range of motion.',reps:'30 sec each side',link:'https://www.youtube.com/results?search_query=TPI+shoulder+mobility+golf+cross+body+stretch'},
  {name:'Wrist & Forearm',desc:'Extend arm with palm out, gently pull fingers back with other hand. Protects against wrist and forearm injuries during the swing.',reps:'30 sec each wrist',link:'https://www.youtube.com/results?search_query=TPI+wrist+forearm+golf+warmup+flexibility'},
  {name:'Club Rotations',desc:'Hold a club across your shoulders and rotate slowly through your full range of motion, simulating the swing sequence.',reps:'15 slow rotations',link:'https://www.youtube.com/results?search_query=TPI+club+across+shoulders+rotation+drill+golf'},
  {name:'Half-Speed Practice Swings',desc:'10 swings at half speed. Focus on sequencing: lower body first, then torso, then arms, then club. This is the kinematic sequence.',reps:'10 swings',link:'https://www.youtube.com/results?search_query=TPI+kinematic+sequence+golf+swing+lower+body+first'}
];

